### ISSUE TITLE
rtl8821cu failed

### ISSUE THREAD

**Issue by CMCCAdmin** [thirdyouth/openwrt-feeds-driver-ext#2]
/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1/os_dep/linux/os_intfs.c:1450:22: note: (near initialization for 'rtw_netdev_ops.ndo_select_queue')
/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1/os_dep/linux/os_intfs.c:2739:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .ndo_select_queue = rtw_select_queue,
                      ^~~~~~~~~~~~~~~~
/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1/os_dep/linux/os_intfs.c:2739:22: note: (near initialization for 'rtw_netdev_vir_if_ops.ndo_select_queue')
cc1: some warnings being treated as errors
scripts/Makefile.build:303: recipe for target '/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1/os_dep/linux/os_intfs.o' failed
make[5]: *** [/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1/os_dep/linux/os_intfs.o] Error 1
Makefile:1520: recipe for target '_module_/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1' failed
make[4]: *** [_module_/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1] Error 2
make[4]: Leaving directory '/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/linux-4.19.108'
Makefile:75: recipe for target '/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1/.built' failed
make[3]: *** [/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1/.built] Error 2
make[3]: Leaving directory '/home/pc/lede/package/kernel/rtl8821cu'
time: package/kernel/rtl8821cu/compile#32.12#2.55#37.03
package/Makefile:111: recipe for target 'package/kernel/rtl8821cu/compile' failed
make[2]: *** [package/kernel/rtl8821cu/compile] Error 2
make[2]: Leaving directory '/home/pc/lede'
package/Makefile:107: recipe for target '/home/pc/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile' failed
make[1]: *** [/home/pc/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/pc/lede'
/home/pc/lede/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by pengphei** [comment]
I have tested the latest source, I have make the rtl8821cu with its source in src. now I can compile it with openwrt 18.02 version. maybe you can make a test. good luck.

**Comment by freedomesitc** [comment]
> /home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1/os_dep/linux/os_intfs.c:1450:22: note: (near initialization for 'rtw_netdev_ops.ndo_select_queue')
> /home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1/os_dep/linux/os_intfs.c:2739:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
> .ndo_select_queue = rtw_select_queue,
> ^~~~~~~~~~~~~~~~
> /home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1/os_dep/linux/os_intfs.c:2739:22: note: (near initialization for 'rtw_netdev_vir_if_ops.ndo_select_queue')
> cc1: some warnings being treated as errors
> scripts/Makefile.build:303: recipe for target '/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1/os_dep/linux/os_intfs.o' failed
> make[5]: *** [/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1/os_dep/linux/os_intfs.o] Error 1
> Makefile:1520: recipe for target '_module_/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1' failed
> make[4]: *** [_module_/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1] Error 2
> make[4]: Leaving directory '/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/linux-4.19.108'
> Makefile:75: recipe for target '/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1/.built' failed
> make[3]: *** [/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-1.0.1/.built] Error 2
> make[3]: Leaving directory '/home/pc/lede/package/kernel/rtl8821cu'
> time: package/kernel/rtl8821cu/compile#32.12#2.55#37.03
> package/Makefile:111: recipe for target 'package/kernel/rtl8821cu/compile' failed
> make[2]: *** [package/kernel/rtl8821cu/compile] Error 2
> make[2]: Leaving directory '/home/pc/lede'
> package/Makefile:107: recipe for target '/home/pc/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile' failed
> make[1]: *** [/home/pc/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
> make[1]: Leaving directory '/home/pc/lede'
> /home/pc/lede/include/toplevel.mk:225: recipe for target 'world' failed
> make: *** [world] Error 2

Is the problem solved? I had the same problem
